=== wewe231223/2026_Graphics/Shader/PSO/Schema.Pipeline.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "./Schema.Pipeline.json",
  "title": "PipelineStateObject Schema",
  "description": "D3D12 PipelineState JSON Schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "version": {
      "type": "number"
    },
    "Name": {
      "type": "string"
    },
    "Type": {
      "enum": [
        "Graphics",
        "Compute"
      ],
      "default": "Graphics"
    },
    "RootSignature": {
      "type": "string"
    },
    "Options": {
      "type": "array",
      "items": {
        "enum": [
          "DepthAlphaCutoff"
        ]
      },
      "uniqueItems": true
    },
    "VS": {
      "$ref": "#/definitions/ShaderStage"
    },
    "PS": {
      "$ref": "#/definitions/ShaderStage"
    },
    "DS": {
      "$ref": "#/definitions/ShaderStage"
    },
    "HS": {
      "$ref": "#/definitions/ShaderStage"
    },
    "GS": {
      "$ref": "#/definitions/ShaderStage"
    },
    "CS": {
      "$ref": "#/definitions/ShaderStage"
    },
    "InputLayout": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/InputElement"
      }
    },
    "StreamOutput": {
      "$ref": "#/definitions/StreamOutput"
    },
    "BlendState": {
      "$ref": "#/definitions/BlendState"
    },
    "SampleMask": {
      "type": "integer",
      "minimum": 0,
      "maximum": 4294967295
    },
    "RasterizerState": {
      "$ref": "#/definitions/RasterizerState"
    },
    "DepthStencilState": {
      "$ref": "#/definitions/DepthStencilState"
    },
    "IBStripCutValue": {
      "enum": [
        "Disabled",
        "0xFFFF",
        "0xFFFFFFFF"
      ],
      "default": "Disabled"
    },
    "PrimitiveTopologyType": {
      "enum": [
        "Undefined",
        "Point",
        "Line",
        "Triangle",
        "Patch"
      ],
      "default": "Triangle"
    },
    "RTVFormats": {
      "type": "array",
      "maxItems": 8,
      "items": {
        "$ref": "#/definitions/Format"
      }
    },
    "DSVFormat": {
      "$ref": "#/definitions/Format"
    },
    "SampleDesc": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Count": {
          "type": "integer",
          "minimum": 0
        },
        "Quality": {
          "type": "integer",
          "minimum": 0
        }
      },
      "required": [
        "Count",
        "Quality"
      ]
    },
    "NodeMask": {
      "type": "integer",
      "minimum": 0
    },
    "Flags": {
      "type": "array",
      "items": {
        "enum": [
          "ToolDebug",
          "DynamicDepthBias"
        ]
      },
      "uniqueItems": true
    }
  },
  "required": [
    "Name",
    "Type",
    "RootSignature"
  ],
  "definitions": {
    "Format": {
      "type": "string",
      "enum": [
        "UNKNOWN",
        "R32G32B32A32_TYPELESS",
        "R32G32B32A32_FLOAT",
        "R32G32B32A32_UINT",
        "R32G32B32A32_SINT",
        "R32G32B32_TYPELESS",
        "R32G32B32_FLOAT",
        "R32G32B32_UINT",
        "R32G32B32_SINT",
        "R16G16B16A16_TYPELESS",
        "R16G16B16A16_FLOAT",
        "R16G16B16A16_UNORM",
        "R16G16B16A16_UINT",
        "R16G16B16A16_SNORM",
        "R16G16B16A16_SINT",
        "R32G32_TYPELESS",
        "R32G32_FLOAT",
        "R32G32_UINT",
        "R32G32_SINT",
        "R32G8X24_TYPELESS",
        "D32_FLOAT_S8X24_UINT",
        "R32_FLOAT_X8X24_TYPELESS",
        "X32_TYPELESS_G8X24_UINT",
        "R10G10B10A2_TYPELESS",
        "R10G10B10A2_UNORM",
        "R10G10B10A2_UINT",
        "R11G11B10_FLOAT",
        "R8G8B8A8_TYPELESS",
        "R8G8B8A8_UNORM",
        "R8G8B8A8_UNORM_SRGB",
        "R8G8B8A8_UINT",
        "R8G8B8A8_SNORM",
        "R8G8B8A8_SINT",
        "R16G16_TYPELESS",
        "R16G16_FLOAT",
        "R16G16_UNORM",
        "R16G16_UINT",
        "R16G16_SNORM",
        "R16G16_SINT",
        "R32_TYPELESS",
        "D32_FLOAT",
        "R32_FLOAT",
        "R32_UINT",
        "R32_SINT",
        "R24G8_TYPELESS",
        "D24_UNORM_S8_UINT",
        "R24_UNORM_X8_TYPELESS",
        "X24_TYPELESS_G8_UINT",
        "R8G8_TYPELESS",
        "R8G8_UNORM",
        "R8G8_UINT",
        "R8G8_SNORM",
        "R8G8_SINT",
        "R16_TYPELESS",
        "R16_FLOAT",
        "D16_UNORM",
        "R16_UNORM",
        "R16_UINT",
        "R16_SNORM",
        "R16_SINT",
        "R8_TYPELESS",
        "R8_UNORM",
        "R8_UINT",
        "R8_SNORM",
        "R8_SINT",
        "A8_UNORM",
        "R1_UNORM",
        "R9G9B9E5_SHAREDEXP",
        "R8G8_B8G8_UNORM",
        "G8R8_G8B8_UNORM",
        "BC1_TYPELESS",
        "BC1_UNORM",
        "BC1_UNORM_SRGB",
        "BC2_TYPELESS",
        "BC2_UNORM",
        "BC2_UNORM_SRGB",
        "BC3_TYPELESS",
        "BC3_UNORM",
        "BC3_UNORM_SRGB",
        "BC4_TYPELESS",
        "BC4_UNORM",
        "BC4_SNORM",
        "BC5_TYPELESS",
        "BC5_UNORM",
        "BC5_SNORM",
        "B5G6R5_UNORM",
        "B5G5R5A1_UNORM",
        "B8G8R8A8_UNORM",
        "B8G8R8X8_UNORM",
        "R10G10B10_XR_BIAS_A2_UNORM",
        "B8G8R8A8_TYPELESS",
        "B8G8R8A8_UNORM_SRGB",
        "B8G8R8X8_TYPELESS",
        "B8G8R8X8_UNORM_SRGB",
        "BC6H_TYPELESS",
        "BC6H_UF16",
        "BC6H_SF16",
        "BC7_TYPELESS",
        "BC7_UNORM",
        "BC7_UNORM_SRGB",
        "AYUV",
        "Y410",
        "Y416",
        "NV12",
        "P010",
        "P016",
        "420_OPAQUE",
        "YUY2",
        "Y210",
        "Y216",
        "NV11",
        "AI44",
        "IA44",
        "P8",
        "A8P8",
        "B4G4R4A4_UNORM",
        "P208",
        "V208",
        "V408",
        "SAMPLER_FEEDBACK_MIN_MIP_OPAQUE",
        "SAMPLER_FEEDBACK_MIP_REGION_USED_OPAQUE"
      ]
    },
    "ShaderStage": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Source": {
          "type": "string"
        },
        "Identifier": {
          "type": "string"
        }
      },
      "required": [
        "Source",
        "Identifier"
      ]
    },
    "InputElement": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "SemanticName": {
          "type": "string"
        },
        "SemanticIndex": {
          "type": "integer",
          "minimum": 0
        },
        "Format": {
          "$ref": "#/definitions/Format"
        },
        "InputSlot": {
          "type": "integer",
          "minimum": 0
        },
        "AlignedByteOffset": {
          "oneOf": [
            {
              "type": "integer",
              "minimum": 0
            },
            {
              "const": 4294967295
            }
          ]
        },
        "InputSlotClass": {
          "enum": [
            "PerVertexData",
            "PerInstanceData"
          ]
        },
        "InstanceDataStepRate": {
          "type": "integer",
          "minimum": 0
        }
      },
      "required": [
        "SemanticName",
        "SemanticIndex",
        "Format",
        "InputSlot",
        "AlignedByteOffset",
        "InputSlotClass",
        "InstanceDataStepRate"
      ]
    },
    "StreamOutput": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Entries": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "Stream": {
                "type": "integer",
                "minimum": 0
              },
              "SemanticName": {
                "type": "string"
              },
              "SemanticIndex": {
                "type": "integer",
                "minimum": 0
              },
              "StartComponent": {
                "type": "integer",
                "minimum": 0
              },
              "ComponentCount": {
                "type": "integer",
                "minimum": 0
              },
              "OutputSlot": {
                "type": "integer",
                "minimum": 0
              }
            },
            "required": [
              "Stream",
              "SemanticName",
              "SemanticIndex",
              "StartComponent",
              "ComponentCount",
              "OutputSlot"
            ]
          }
        },
        "BufferStrides": {
          "type": "array",
          "items": {
            "type": "integer",
            "minimum": 0
          }
        }
      }
    },
    "BlendState": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "AlphaToCoverageEnable": {
          "type": "boolean"
        },
        "IndependentBlendEnable": {
          "type": "boolean"
        },
        "RenderTargets": {
          "type": "array",
          "maxItems": 8,
          "items": {
            "$ref": "#/definitions/RenderTargetBlendDesc"
          }
        }
      }
    },
    "RenderTargetBlendDesc": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "BlendEnable": {
          "type": "boolean"
        },
        "LogicOpEnable": {
          "type": "boolean"
        },
        "SrcBlend": {
          "enum": [
            "One",
            "Zero",
            "SrcColor",
            "InvSrcColor",
            "SrcAlpha",
            "InvSrcAlpha",
            "DestAlpha",
            "InvDestAlpha",
            "DestColor",
            "InvDestColor",
            "SrcAlphaSat",
            "BlendFactor",
            "InvBlendFactor",
            "Src1Color",
            "InvSrc1Color",
            "Src1Alpha",
            "InvSrc1Alpha"
          ]
        },
        "DestBlend": {
          "enum": [
            "One",
            "Zero",
            "SrcColor",
            "InvSrcColor",
            "SrcAlpha",
            "InvSrcAlpha",
            "DestAlpha",
            "InvDestAlpha",
            "DestColor",
            "InvDestColor",
            "SrcAlphaSat",
            "BlendFactor",
            "InvBlendFactor",
            "Src1Color",
            "InvSrc1Color",
            "Src1Alpha",
            "InvSrc1Alpha"
          ]
        },
        "BlendOp": {
          "enum": [
            "Add",
            "Subtract",
            "RevSubtract",
            "Min",
            "Max"
          ]
        },
        "SrcBlendAlpha": {
          "enum": [
            "One",
            "Zero",
            "SrcColor",
            "InvSrcColor",
            "SrcAlpha",
            "InvSrcAlpha",
            "DestAlpha",
            "InvDestAlpha",
            "DestColor",
            "InvDestColor",
            "SrcAlphaSat",
            "BlendFactor",
            "InvBlendFactor",
            "Src1Color",
            "InvSrc1Color",
            "Src1Alpha",
            "InvSrc1Alpha"
          ]
        },
        "DestBlendAlpha": {
          "enum": [
            "One",
            "Zero",
            "SrcColor",
            "InvSrcColor",
            "SrcAlpha",
            "InvSrcAlpha",
            "DestAlpha",
            "InvDestAlpha",
            "DestColor",
            "InvDestColor",
            "SrcAlphaSat",
            "BlendFactor",
            "InvBlendFactor",
            "Src1Color",
            "InvSrc1Color",
            "Src1Alpha",
            "InvSrc1Alpha"
          ]
        },
        "BlendOpAlpha": {
          "enum": [
            "Add",
            "Subtract",
            "RevSubtract",
            "Min",
            "Max"
          ]
        },
        "LogicOp": {
          "enum": [
            "Clear",
            "Set",
            "Copy",
            "CopyInverted",
            "Noop",
            "Invert",
            "And",
            "Nand",
            "Or",
            "Nor",
            "Xor",
            "Equiv",
            "AndReverse",
            "AndInverted",
            "OrReverse",
            "OrInverted"
          ]
        },
        "RenderTargetWriteMask": {
          "type": "integer",
          "minimum": 0,
          "maximum": 15
        }
      }
    },
    "RasterizerState": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "FillMode": {
          "enum": [
            "Solid",
            "Wireframe"
          ]
        },
        "CullMode": {
          "enum": [
            "None",
            "Front",
            "Back"
          ]
        },
        "FrontCounterClockwise": {
          "type": "boolean"
        },
        "DepthBias": {
          "type": "integer"
        },
        "DepthBiasClamp": {
          "type": "number"
        },
        "SlopeScaledDepthBias": {
          "type": "number"
        },
        "DepthClipEnable": {
          "type": "boolean"
        },
        "MultisampleEnable": {
          "type": "boolean"
        },
        "AntialiasedLineEnable": {
          "type": "boolean"
        },
        "ForcedSampleCount": {
          "type": "integer",
          "minimum": 0
        },
        "ConservativeRaster": {
          "enum": [
            "Off",
            "On"
          ]
        }
      }
    },
    "DepthStencilState": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "DepthEnable": {
          "type": "boolean"
        },
        "DepthWriteMask": {
          "enum": [
            "Zero",
            "All"
          ]
        },
        "DepthFunc": {
          "enum": [
            "Never",
            "Less",
            "Equal",
            "LessEqual",
            "Greater",
            "NotEqual",
            "GreaterEqual",
            "Always"
          ]
        },
        "StencilEnable": {
          "type": "boolean"
        },
        "StencilReadMask": {
          "type": "integer",
          "minimum": 0,
          "maximum": 255
        },
        "StencilWriteMask": {
          "type": "integer",
          "minimum": 0,
          "maximum": 255
        },
        "FrontFace": {
          "$ref": "#/definitions/DepthStencilOpDesc"
        },
        "BackFace": {
          "$ref": "#/definitions/DepthStencilOpDesc"
        }
      }
    },
    "DepthStencilOpDesc": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "StencilFailOp": {
          "enum": [
            "Keep",
            "Zero",
            "Replace",
            "IncrSat",
            "DecrSat",
            "Invert",
            "Incr",
            "Decr"
          ]
        },
        "StencilDepthFailOp": {
          "enum": [
            "Keep",
            "Zero",
            "Replace",
            "IncrSat",
            "DecrSat",
            "Invert",
            "Incr",
            "Decr"
          ]
        },
        "StencilPassOp": {
          "enum": [
            "Keep",
            "Zero",
            "Replace",
            "IncrSat",
            "DecrSat",
            "Invert",
            "Incr",
            "Decr"
          ]
        },
        "StencilFunc": {
          "enum": [
            "Never",
            "Less",
            "Equal",
            "LessEqual",
            "Greater",
            "NotEqual",
            "GreaterEqual",
            "Always"
          ]
        }
      }
    }
  },
  "allOf": [
    {
      "if": {
        "properties": {
          "Type": {
            "const": "Graphics"
          }
        }
      },
      "then": {
        "required": [
          "VS",
          "PS"
        ]
      }
    },
    {
      "if": {
        "properties": {
          "Type": {
            "const": "Compute"
          }
        }
      },
      "then": {
        "required": [
          "CS"
        ]
      }
    }
  ]
}

=== wewe231223/2026_Graphics/Shader/PSO/BoundingBoxLineGraphics.json
{
  "$schema": "./Schema.Pipeline.json",
  "Name": "BoundingBoxLineGraphics",
  "Type": "Graphics",
  "RootSignature": "DefaultRootSignature",
  "VS": {
    "Source": "BoundingBoxLineShader.hlsl",
    "Identifier": "vs_6_6:VsMain"
  },
  "GS": {
    "Source": "BoundingBoxLineShader.hlsl",
    "Identifier": "gs_6_6:GsMain"
  },
  "PS": {
    "Source": "BoundingBoxLineShader.hlsl",
    "Identifier": "ps_6_6:PsMain"
  },
  "BlendState": {
    "AlphaToCoverageEnable": false,
    "IndependentBlendEnable": false,
    "RenderTargets": [
      {
        "BlendEnable": false,
        "BlendOp": "Add",
        "BlendOpAlpha": "Add",
        "DestBlend": "Zero",
        "DestBlendAlpha": "Zero",
        "LogicOp": "Noop",
        "LogicOpEnable": false,
        "RenderTargetWriteMask": 15,
        "SrcBlend": "One",
        "SrcBlendAlpha": "One"
      }
    ]
  },
  "SampleMask": 4294967295,
  "RasterizerState": {
    "FillMode": "Solid",
    "CullMode": "None",
    "FrontCounterClockwise": false,
    "DepthBias": 0,
    "DepthBiasClamp": 0,
    "SlopeScaledDepthBias": 0,
    "DepthClipEnable": true,
    "MultisampleEnable": false,
    "AntialiasedLineEnable": false,
    "ForcedSampleCount": 0,
    "ConservativeRaster": "Off"
  },
  "DepthStencilState": {
    "DepthEnable": true,
    "DepthWriteMask": "Zero",
    "DepthFunc": "LessEqual",
    "StencilEnable": false,
    "StencilReadMask": 255,
    "StencilWriteMask": 255,
    "FrontFace": {
      "StencilFailOp": "Keep",
      "StencilDepthFailOp": "Keep",
      "StencilPassOp": "Keep",
      "StencilFunc": "Always"
    },
    "BackFace": {
      "StencilFailOp": "Keep",
      "StencilDepthFailOp": "Keep",
      "StencilPassOp": "Keep",
      "StencilFunc": "Always"
    }
  },
  "IBStripCutValue": "Disabled",
  "PrimitiveTopologyType": "Point",
  "RTVFormats": [
    "R8G8B8A8_UNORM"
  ],
  "DSVFormat": "D32_FLOAT",
  "SampleDesc": {
    "Count": 1,
    "Quality": 0
  },
  "NodeMask": 0,
  "Flags": []
}

=== wewe231223/2026_Graphics/Shader/PSO/EnvironmentObjectGraphics.json
{
  "$schema": "./Schema.Pipeline.json",
  "Name": "EnvironmentObjectGraphics",
  "Type": "Graphics",
  "Options": [
    "DepthAlphaCutoff"
  ],
  "RootSignature": "DefaultRootSignature",
  "VS": {
    "Source": "EnvironmentObjectShader.hlsl",
    "Identifier": "vs_6_6:VsMain"
  },
  "PS": {
    "Source": "EnvironmentObjectShader.hlsl",
    "Identifier": "ps_6_6:PsMain"
  },
  "InputLayout": [
    {
      "SemanticName": "POSITION",
      "SemanticIndex": 0,
      "Format": "R32G32B32_FLOAT",
      "InputSlot": 0,
      "AlignedByteOffset": 0,
      "InputSlotClass": "PerVertexData",
      "InstanceDataStepRate": 0
    },
    {
      "SemanticName": "NORMAL",
      "SemanticIndex": 0,
      "Format": "R32G32B32_FLOAT",
      "InputSlot": 1,
      "AlignedByteOffset": 0,
      "InputSlotClass": "PerVertexData",
      "InstanceDataStepRate": 0
    },
    {
      "SemanticName": "TEXCOORD",
      "SemanticIndex": 0,
      "Format": "R32G32_FLOAT",
      "InputSlot": 2,
      "AlignedByteOffset": 0,
      "InputSlotClass": "PerVertexData",
      "InstanceDataStepRate": 0
    },
    {
      "SemanticName": "TANGENT",
      "SemanticIndex": 0,
      "Format": "R32G32B32_FLOAT",
      "InputSlot": 3,
      "AlignedByteOffset": 0,
      "InputSlotClass": "PerVertexData",
      "InstanceDataStepRate": 0
    },
    {
      "SemanticName": "BITANGENT",
      "SemanticIndex": 0,
      "Format": "R32G32B32_FLOAT",
      "InputSlot": 4,
      "AlignedByteOffset": 0,
      "InputSlotClass": "PerVertexData",
      "InstanceDataStepRate": 0
    }
  ],
  "BlendState": {
    "AlphaToCoverageEnable": false,
    "IndependentBlendEnable": false,
    "RenderTargets": [
      {
        "BlendEnable": false,
        "BlendOp": "Add",
        "BlendOpAlpha": "Add",
        "DestBlend": "Zero",
        "DestBlendAlpha": "Zero",
        "LogicOp": "Noop",
        "LogicOpEnable": false,
        "RenderTargetWriteMask": 15,
        "SrcBlend": "One",
        "SrcBlendAlpha": "One"
      }
    ]
  },
  "SampleMask": 4294967295,
  "RasterizerState": {
    "FillMode": "Solid",
    "CullMode": "None",
    "FrontCounterClockwise": false,
    "DepthBias": 0,
    "DepthBiasClamp": 0,
    "SlopeScaledDepthBias": 0,
    "DepthClipEnable": true,
    "MultisampleEnable": false,
    "AntialiasedLineEnable": false,
    "ForcedSampleCount": 0,
    "ConservativeRaster": "Off"
  },
  "DepthStencilState": {
    "DepthEnable": true,
    "DepthWriteMask": "All",
    "DepthFunc": "Less",
    "StencilEnable": false,
    "StencilReadMask": 255,
    "StencilWriteMask": 255,
    "FrontFace": {
      "StencilFailOp": "Keep",
      "StencilDepthFailOp": "Keep",
      "StencilPassOp": "Keep",
      "StencilFunc": "Always"
    },
    "BackFace": {
      "StencilFailOp": "Keep",
      "StencilDepthFailOp": "Keep",
      "StencilPassOp": "Keep",
      "StencilFunc": "Always"
    }
  },
  "IBStripCutValue": "Disabled",
  "PrimitiveTopologyType": "Triangle",
  "RTVFormats": [
    "R8G8B8A8_UNORM",
    "R16G16B16A16_FLOAT",
    "R32G32B32A32_FLOAT"
  ],
  "DSVFormat": "D24_UNORM_S8_UINT",
  "SampleDesc": {
    "Count": 1,
    "Quality": 0
  },
  "NodeMask": 0,
  "Flags": []
}

=== wewe231223/2026_Graphics/Shader/PSO/DebugGeometryGraphics.json
{
  "$schema": "./Schema.Pipeline.json",
  "Name": "DebugGeometryGraphics",
  "Type": "Graphics",
  "RootSignature": "DefaultRootSignature",
  "VS": {
    "Source": "DebugGeometryShader.hlsl",
    "Identifier": "vs_6_6:VsMain"
  },
  "GS": {
    "Source": "DebugGeometryShader.hlsl",
    "Identifier": "gs_6_6:GsMain"
  },
  "PS": {
    "Source": "DebugGeometryShader.hlsl",
    "Identifier": "ps_6_6:PsMain"
  },
  "BlendState": {
    "AlphaToCoverageEnable": false,
    "IndependentBlendEnable": false,
    "RenderTargets": [
      {
        "BlendEnable": false,
        "BlendOp": "Add",
        "BlendOpAlpha": "Add",
        "DestBlend": "Zero",
        "DestBlendAlpha": "Zero",
        "LogicOp": "Noop",
        "LogicOpEnable": false,
        "RenderTargetWriteMask": 15,
        "SrcBlend": "One",
        "SrcBlendAlpha": "One"
      }
    ]
  },
  "SampleMask": 4294967295,
  "RasterizerState": {
    "FillMode": "Solid",
    "CullMode": "None",
    "FrontCounterClockwise": false,
    "DepthBias": 0,
    "DepthBiasClamp": 0,
    "SlopeScaledDepthBias": 0,
    "DepthClipEnable": true,
    "MultisampleEnable": false,
    "AntialiasedLineEnable": false,
    "ForcedSampleCount": 0,
    "ConservativeRaster": "Off"
  },
  "DepthStencilState": {
    "DepthEnable": true,
    "DepthWriteMask": "Zero",
    "DepthFunc": "LessEqual",
    "StencilEnable": false,
    "StencilReadMask": 255,
    "StencilWriteMask": 255,
    "FrontFace": {
      "StencilFailOp": "Keep",
      "StencilDepthFailOp": "Keep",
      "StencilPassOp": "Keep",
      "StencilFunc": "Always"
    },
    "BackFace": {
      "StencilFailOp": "Keep",
      "StencilDepthFailOp": "Keep",
      "StencilPassOp": "Keep",
      "StencilFunc": "Always"
    }
  },
  "IBStripCutValue": "Disabled",
  "PrimitiveTopologyType": "Point",
  "RTVFormats": [
    "R8G8B8A8_UNORM"
  ],
  "DSVFormat": "D24_UNORM_S8_UINT",
  "SampleDesc": {
    "Count": 1,
    "Quality": 0
  },
  "NodeMask": 0,
  "Flags": []
}

=== wewe231223/2026_Graphics/Shader/PSO/SkyDomeGraphics.json
{
  "$schema": "./Schema.Pipeline.json",
  "Name": "SkyDomeGraphics",
  "Type": "Graphics",
  "RootSignature": "DefaultRootSignature",
  "VS": {
    "Source": "SkyDomeShader.hlsl",
    "Identifier": "vs_6_6:VsMain"
  },
  "PS": {
    "Source": "SkyDomeShader.hlsl",
    "Identifier": "ps_6_6:PsMain"
  },
  "InputLayout": [
    {
      "SemanticName": "POSITION",
      "SemanticIndex": 0,
      "Format": "R32G32B32_FLOAT",
      "InputSlot": 0,
      "AlignedByteOffset": 0,
      "InputSlotClass": "PerVertexData",
      "InstanceDataStepRate": 0
    },
    {
      "SemanticName": "NORMAL",
      "SemanticIndex": 0,
      "Format": "R32G32B32_FLOAT",
      "InputSlot": 1,
      "AlignedByteOffset": 0,
      "InputSlotClass": "PerVertexData",
      "InstanceDataStepRate": 0
    },
    {
      "SemanticName": "TEXCOORD",
      "SemanticIndex": 0,
      "Format": "R32G32_FLOAT",
      "InputSlot": 2,
      "AlignedByteOffset": 0,
      "InputSlotClass": "PerVertexData",
      "InstanceDataStepRate": 0
    },
    {
      "SemanticName": "COLOR",
      "SemanticIndex": 0,
      "Format": "R32G32B32A32_FLOAT",
      "InputSlot": 3,
      "AlignedByteOffset": 0,
      "InputSlotClass": "PerVertexData",
      "InstanceDataStepRate": 0
    }
  ],
  "BlendState": {
    "AlphaToCoverageEnable": false,
    "IndependentBlendEnable": false,
    "RenderTargets": [
      {
        "BlendEnable": false,
        "BlendOp": "Add",
        "BlendOpAlpha": "Add",
        "DestBlend": "Zero",
        "DestBlendAlpha": "Zero",
        "LogicOp": "Noop",
        "LogicOpEnable": false,
        "RenderTargetWriteMask": 15,
        "SrcBlend": "One",
        "SrcBlendAlpha": "One"
      }
    ]
  },
  "SampleMask": 4294967295,
  "RasterizerState": {
    "FillMode": "Solid",
    "CullMode": "Back",
    "FrontCounterClockwise": false,
    "DepthBias": 0,
    "DepthBiasClamp": 0,
    "SlopeScaledDepthBias": 0,
    "DepthClipEnable": true,
    "MultisampleEnable": false,
    "AntialiasedLineEnable": false,
    "ForcedSampleCount": 0,
    "ConservativeRaster": "Off"
  },
  "DepthStencilState": {
    "DepthEnable": true,
    "DepthWriteMask": "Zero",
    "DepthFunc": "LessEqual",
    "StencilEnable": false,
    "StencilReadMask": 255,
    "StencilWriteMask": 255,
    "FrontFace": {
      "StencilFailOp": "Keep",
      "StencilDepthFailOp": "Keep",
      "StencilPassOp": "Keep",
      "StencilFunc": "Always"
    },
    "BackFace": {
      "StencilFailOp": "Keep",
      "StencilDepthFailOp": "Keep",
      "StencilPassOp": "Keep",
      "StencilFunc": "Always"
    }
  },
  "IBStripCutValue": "Disabled",
  "PrimitiveTopologyType": "Triangle",
  "RTVFormats": [
    "R8G8B8A8_UNORM"
  ],
  "DSVFormat": "D24_UNORM_S8_UINT",
  "SampleDesc": {
    "Count": 1,
    "Quality": 0
  },
  "NodeMask": 0,
  "Flags": []
}

=== wewe231223/2026_Graphics/Shader/PSO/SkinnedGraphics.json
{
  "$schema": "./Schema.Pipeline.json",
  "Name": "SkinnedGraphics",
  "Type": "Graphics",
  "RootSignature": "DefaultRootSignature",
  "VS": {
    "Source": "SkinnedMeshShader.hlsl",
    "Identifier": "vs_6_6:VsMain"
  },
  "PS": {
    "Source": "SkinnedMeshShader.hlsl",
    "Identifier": "ps_6_6:PsMain"
  },
  "InputLayout": [
    {
      "SemanticName": "POSITION",
      "SemanticIndex": 0,
      "Format": "R32G32B32_FLOAT",
      "InputSlot": 0,
      "AlignedByteOffset": 0,
      "InputSlotClass": "PerVertexData",
      "InstanceDataStepRate": 0
    },
    {
      "SemanticName": "NORMAL",
      "SemanticIndex": 0,
      "Format": "R32G32B32_FLOAT",
      "InputSlot": 1,
      "AlignedByteOffset": 0,
      "InputSlotClass": "PerVertexData",
      "InstanceDataStepRate": 0
    },
    {
      "SemanticName": "TEXCOORD",
      "SemanticIndex": 0,
      "Format": "R32G32_FLOAT",
      "InputSlot": 2,
      "AlignedByteOffset": 0,
      "InputSlotClass": "PerVertexData",
      "InstanceDataStepRate": 0
    },
    {
      "SemanticName": "BLENDINDICES",
      "SemanticIndex": 0,
      "Format": "R32G32B32A32_UINT",
      "InputSlot": 3,
      "AlignedByteOffset": 0,
      "InputSlotClass": "PerVertexData",
      "InstanceDataStepRate": 0
    },
    {
      "SemanticName": "BLENDWEIGHT",
      "SemanticIndex": 0,
      "Format": "R32G32B32A32_FLOAT",
      "InputSlot": 4,
      "AlignedByteOffset": 0,
      "InputSlotClass": "PerVertexData",
      "InstanceDataStepRate": 0
    }
  ],
  "BlendState": {
    "AlphaToCoverageEnable": false,
    "IndependentBlendEnable": false,
    "RenderTargets": [
      {
        "BlendEnable": false,
        "BlendOp": "Add",
        "BlendOpAlpha": "Add",
        "DestBlend": "Zero",
        "DestBlendAlpha": "Zero",
        "LogicOp": "Noop",
        "LogicOpEnable": false,
        "RenderTargetWriteMask": 15,
        "SrcBlend": "One",
        "SrcBlendAlpha": "One"
      }
    ]
  },
  "SampleMask": 4294967295,
  "RasterizerState": {
    "FillMode": "Solid",
    "CullMode": "Back",
    "FrontCounterClockwise": false,
    "DepthBias": 4096,
    "DepthBiasClamp": 0.01,
    "SlopeScaledDepthBias": 1.5,
    "DepthClipEnable": true,
    "MultisampleEnable": false,
    "AntialiasedLineEnable": false,
    "ForcedSampleCount": 0,
    "ConservativeRaster": "Off"
  },
  "DepthStencilState": {
    "DepthEnable": true,
    "DepthWriteMask": "All",
    "DepthFunc": "Less",
    "StencilEnable": false,
    "StencilReadMask": 255,
    "StencilWriteMask": 255,
    "FrontFace": {
      "StencilFailOp": "Keep",
      "StencilDepthFailOp": "Keep",
      "StencilPassOp": "Keep",
      "StencilFunc": "Always"
    },
    "BackFace": {
      "StencilFailOp": "Keep",
      "StencilDepthFailOp": "Keep",
      "StencilPassOp": "Keep",
      "StencilFunc": "Always"
    }
  },
  "IBStripCutValue": "Disabled",
  "PrimitiveTopologyType": "Triangle",
  "RTVFormats": [
    "R8G8B8A8_UNORM",
    "R16G16B16A16_FLOAT",
    "R32G32B32A32_FLOAT"
  ],
  "DSVFormat": "D24_UNORM_S8_UINT",
  "SampleDesc": {
    "Count": 1,
    "Quality": 0
  },
  "NodeMask": 0,
  "Flags": []
}
