=== wewe231223/2026_Graphics/Shader/RS/Schema.RootSignature.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "./Schema.RootSignature.json",
  "title": "RootSignature Schema",
  "description": "D3D12 RootSignature JSON Schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "version": {
      "type": "number"
    },
    "Name": {
      "type": "string"
    },
    "Flags": {
      "type": "array",
      "items": {
        "enum": [
          "AllowInputAssemblerInputLayout",
          "DenyVertexShaderRootAccess",
          "DenyHullShaderRootAccess",
          "DenyDomainShaderRootAccess",
          "DenyGeometryShaderRootAccess",
          "DenyPixelShaderRootAccess",
          "AllowStreamOutput",
          "LocalRootSignature",
          "DenyAmplificationShaderRootAccess",
          "DenyMeshShaderRootAccess",
          "CBVSRVUAVHeapDirectlyIndexed",
          "SamplerHeapDirectlyIndexed"
        ]
      },
      "uniqueItems": true
    },
    "Parameters": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/RootParameter"
      }
    },
    "StaticSamplers": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/StaticSampler"
      }
    }
  },
  "required": [
    "Name"
  ],
  "definitions": {
    "ShaderVisibility": {
      "type": "string",
      "enum": [
        "All",
        "Vertex",
        "Hull",
        "Domain",
        "Geometry",
        "Pixel",
        "Amplification",
        "Mesh"
      ]
    },
    "RootParameter": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Type": {
          "enum": [
            "DescriptorTable",
            "CBV",
            "SRV",
            "UAV",
            "Constants"
          ]
        },
        "ShaderVisibility": {
          "$ref": "#/definitions/ShaderVisibility"
        },
        "DescriptorTable": {
          "$ref": "#/definitions/DescriptorTable"
        },
        "Descriptor": {
          "$ref": "#/definitions/RootDescriptor"
        },
        "Constants": {
          "$ref": "#/definitions/RootConstants"
        }
      },
      "required": [
        "Type",
        "ShaderVisibility"
      ],
      "allOf": [
        {
          "if": {
            "properties": {
              "Type": {
                "const": "DescriptorTable"
              }
            }
          },
          "then": {
            "required": [
              "DescriptorTable"
            ]
          }
        },
        {
          "if": {
            "properties": {
              "Type": {
                "enum": [
                  "CBV",
                  "SRV",
                  "UAV"
                ]
              }
            }
          },
          "then": {
            "required": [
              "Descriptor"
            ]
          }
        },
        {
          "if": {
            "properties": {
              "Type": {
                "const": "Constants"
              }
            }
          },
          "then": {
            "required": [
              "Constants"
            ]
          }
        }
      ]
    },
    "DescriptorTable": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Ranges": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/DescriptorRange"
          }
        }
      },
      "required": [
        "Ranges"
      ]
    },
    "DescriptorRange": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "RangeType": {
          "enum": [
            "SRV",
            "UAV",
            "CBV",
            "Sampler"
          ]
        },
        "NumDescriptors": {
          "type": "integer",
          "minimum": 0
        },
        "BaseShaderRegister": {
          "type": "integer",
          "minimum": 0
        },
        "RegisterSpace": {
          "type": "integer",
          "minimum": 0
        },
        "OffsetInDescriptorsFromTableStart": {
          "oneOf": [
            {
              "type": "integer",
              "minimum": 0
            },
            {
              "const": 4294967295
            }
          ]
        },
        "Flags": {
          "type": "array",
          "items": {
            "enum": [
              "DescriptorsVolatile",
              "DataVolatile",
              "DataStaticWhileSetAtExecute",
              "DataStatic",
              "DescriptorsStaticKeepingBufferBoundsChecks"
            ]
          },
          "uniqueItems": true
        }
      },
      "required": [
        "RangeType",
        "NumDescriptors",
        "BaseShaderRegister",
        "RegisterSpace"
      ]
    },
    "RootDescriptor": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "ShaderRegister": {
          "type": "integer",
          "minimum": 0
        },
        "RegisterSpace": {
          "type": "integer",
          "minimum": 0
        },
        "Flags": {
          "type": "array",
          "items": {
            "enum": [
              "DataVolatile",
              "DataStaticWhileSetAtExecute",
              "DataStatic"
            ]
          },
          "uniqueItems": true
        }
      },
      "required": [
        "ShaderRegister",
        "RegisterSpace"
      ]
    },
    "RootConstants": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "ShaderRegister": {
          "type": "integer",
          "minimum": 0
        },
        "RegisterSpace": {
          "type": "integer",
          "minimum": 0
        },
        "Num32BitValues": {
          "type": "integer",
          "minimum": 0
        }
      },
      "required": [
        "ShaderRegister",
        "RegisterSpace",
        "Num32BitValues"
      ]
    },
    "StaticSampler": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Filter": {
          "enum": [
            "MinMagMipPoint",
            "MinMagPointMipLinear",
            "MinPointMagLinearMipPoint",
            "MinPointMagMipLinear",
            "MinLinearMagMipPoint",
            "MinLinearMagPointMipLinear",
            "MinMagLinearMipPoint",
            "MinMagMipLinear",
            "Anisotropic",
            "ComparisonMinMagMipPoint",
            "ComparisonMinMagPointMipLinear",
            "ComparisonMinPointMagLinearMipPoint",
            "ComparisonMinPointMagMipLinear",
            "ComparisonMinLinearMagMipPoint",
            "ComparisonMinLinearMagPointMipLinear",
            "ComparisonMinMagLinearMipPoint",
            "ComparisonMinMagMipLinear",
            "ComparisonAnisotropic"
          ]
        },
        "AddressU": {
          "enum": [
            "Wrap",
            "Mirror",
            "Clamp",
            "Border",
            "MirrorOnce"
          ]
        },
        "AddressV": {
          "enum": [
            "Wrap",
            "Mirror",
            "Clamp",
            "Border",
            "MirrorOnce"
          ]
        },
        "AddressW": {
          "enum": [
            "Wrap",
            "Mirror",
            "Clamp",
            "Border",
            "MirrorOnce"
          ]
        },
        "MipLODBias": {
          "type": "number"
        },
        "MaxAnisotropy": {
          "type": "integer",
          "minimum": 0
        },
        "ComparisonFunc": {
          "enum": [
            "Never",
            "Less",
            "Equal",
            "LessEqual",
            "Greater",
            "NotEqual",
            "GreaterEqual",
            "Always"
          ]
        },
        "BorderColor": {
          "enum": [
            "TransparentBlack",
            "OpaqueBlack",
            "OpaqueWhite"
          ]
        },
        "MinLOD": {
          "type": "number"
        },
        "MaxLOD": {
          "type": "number"
        },
        "ShaderRegister": {
          "type": "integer",
          "minimum": 0
        },
        "RegisterSpace": {
          "type": "integer",
          "minimum": 0
        },
        "ShaderVisibility": {
          "$ref": "#/definitions/ShaderVisibility"
        }
      },
      "required": [
        "Filter",
        "AddressU",
        "AddressV",
        "AddressW",
        "MipLODBias",
        "MaxAnisotropy",
        "ComparisonFunc",
        "BorderColor",
        "MinLOD",
        "MaxLOD",
        "ShaderRegister",
        "RegisterSpace",
        "ShaderVisibility"
      ]
    }
  }
}

=== wewe231223/2026_Graphics/Shader/RS/DefaultRootSignature.json
{
  "$schema": "./Schema.RootSignature.json",
  "Name": "DefaultRootSignature",
  "Flags": [
    "AllowInputAssemblerInputLayout",
    "CBVSRVUAVHeapDirectlyIndexed"
  ],
  "Parameters": [
    {
      "Type": "Constants",
      "ShaderVisibility": "All",
      "Constants": {
        "ShaderRegister": 1,
        "RegisterSpace": 0,
        "Num32BitValues": 12
      }
    }
  ],
  "StaticSamplers": [
    {
      "Filter": "Anisotropic",
      "AddressU": "Wrap",
      "AddressV": "Wrap",
      "AddressW": "Wrap",
      "MipLODBias": 0.0,
      "MaxAnisotropy": 1,
      "ComparisonFunc": "Always",
      "BorderColor": "OpaqueBlack",
      "MinLOD": 0.0,
      "MaxLOD": 3.402823466e+38,
      "ShaderRegister": 0,
      "RegisterSpace": 0,
      "ShaderVisibility": "Pixel"
    },
    {
      "Filter": "ComparisonMinMagLinearMipPoint",
      "AddressU": "Clamp",
      "AddressV": "Clamp",
      "AddressW": "Clamp",
      "MipLODBias": 0.0,
      "MaxAnisotropy": 1,
      "ComparisonFunc": "LessEqual",
      "BorderColor": "OpaqueWhite",
      "MinLOD": 0.0,
      "MaxLOD": 3.402823466e+38,
      "ShaderRegister": 1,
      "RegisterSpace": 0,
      "ShaderVisibility": "Pixel"
    }
  ]
}
